version: '3'
services:
  foundryvtt:
    container_name: foundryvtt
    image: shoyuvanilla/foundryvtt
    ports:
      - "80:30000"
    restart: always
    volumes:
      - ./foundryvtt:/foundryvtt
      - ./foundrydata:/root/.local/share/FoundryVTT

  filegator:
    container_name: filegator
    image: shoyuvanilla/filegator
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./:/var/www/html/filegator/repository
      - ./filegator-configuration.php:/var/www/html/filegator/configuration.php