version: '3'
services:
  foundryvtt:
    container_name: foundryvtt
    image: shoyuvanilla/foundryvtt
    restart: always
    volumes:
      - ./foundryvtt:/foundryvtt
      - ./foundrydata:/root/.local/share/FoundryVTT

  filegator:
    container_name: filegator
    image: shoyuvanilla/filegator
    restart: always
    volumes:
      - ./:/var/www/html/filegator/repository
      - ./filegator-configuration.php:/var/www/html/filegator/configuration.php

  https-portal:
    container_name: https-portal
    image: steveltn/https-portal
    ports:
      - 80:80
      - 443:443
    restart: always
    environment:
      STAGE: production
      PROXY_READ_TIMEOUT: 3600
      CLIENT_MAX_BODY_SIZE: 200M
      WEBSOCKET: 'true'
    volumes:
      - ssl-certs:/var/lib/https-portal

volumes:
  ssl-certs: {}